<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>structx-column</artifactId>
        <groupId>org.datayoo.sengee</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>structx-column-descriptor</artifactId>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.datayoo.sengee</groupId>
            <artifactId>sengee-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.sengee</groupId>
            <artifactId>descriptor-operators-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.sengee</groupId>
            <artifactId>sengee-datax</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.sengee</groupId>
            <artifactId>prox-common-descriptor</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.sengee</groupId>
            <artifactId>iox-rw-descriptor</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.footstone</groupId>
            <artifactId>footstone-configx</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.footstone</groupId>
            <artifactId>footstone-flowx</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.footstone</groupId>
            <artifactId>footstone-datax</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.footstone</groupId>
            <artifactId>footstone-common</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.footstone</groupId>
            <artifactId>footstone-sightx</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.moql</groupId>
            <artifactId>moql-engine</artifactId>
            <version>1.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.datayoo.moql</groupId>
            <artifactId>moql-meta</artifactId>
            <version>1.2.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.datayoo.pluginx</groupId>
                <artifactId>descriptor-plugin</artifactId>
                <version>1.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <id>descriptor-pack</id>
                        <goals>
                            <goal>descriptorPack</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.datayoo.pluginx</groupId>
                <artifactId>i18n-maven-plugin</artifactId>
                <version>1.0-SNAPSHOT</version>
            </plugin>
        </plugins>
    </build>
</project>